config/routes.rb
Rails.application.routes.draw do
  # resources :locations
  # resources :vehicles
  root to:  'vehicles#index'
  post '/vehicles', to: 'vehicles#create', as: 'create_vehicle'
  post '/vehicles/:id/locations', to: 'locations#create', as: 'create_location'
  get '/all_vehicles_locations', to: 'locations#all_vehicles_locations', as: 'all_vehicles_locations'
  delete '/vehicles/:id', to: 'vehicles#destroy' , as: 'destroy'
  delete '/locations/reset', to: 'locations#reset' , as: 'reset'

end

app/models/location.rb
class Location
  include Mongoid::Document
  include Mongoid::Timestamps

  field :lat, type: BigDecimal
  field :lng, type: BigDecimal
  field :at, type: DateTime
  embedded_in :vehicle
end

app/models/vehicle.rb
class Vehicle
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :locations
  accepts_nested_attributes_for :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_vehicle, only: [:create]
  before_action :location_params, only: [:create]

  # no need to protect against cross site scripting for now
  protect_from_forgery with: :null_session

  # display all vehicles last locations
  # it runs much faster using mongoDB compared to relational database
  def all_vehicles_locations
    @vehicles_last_location = {}
    @locations = Vehicle.all.map { |vehicle| @vehicles_last_location[vehicle.id] = vehicle.locations.last ?
                                                                                       {lat: vehicle.locations.last.lat, lng: vehicle.locations.last.lng} : {} }
    render json: @vehicles_last_location
  end

  # POST /locations
  def create
    @vehicle.locations << Location.new(lng: params[:location][:lng],
                                       lat: params[:location][:lat],
                                       at: params[:location][:at])
    @vehicle.save!
  end


  def reset
    Vehicle.all.map{|vehicle| vehicle.locations.destroy_all}
    Vehicle.destroy_all
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:lat, :lng, :at)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:destroy]
  protect_from_forgery with: :null_session

  # GET /vehicles
  def index
    @vehicles = Vehicle.all.pluck(:id)
  end



  # POST /vehicles
  def create
    @vehicle = Vehicle.find_or_create_by!(id:params[:id])
  end

  # DELETE /vehicles/:id
  # destroy all vehicles locations
  def destroy
    @vehicle.locations.destroy_all
  end

  private
  
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AllygatorShuttle</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <%#= javascript_include_tag 'application' %>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <script src="//maps.google.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API']%>"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
  <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'></script>
  <script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'></script>
</head>

<body>


<%= yield %>

</body>


<script>

</script>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="field">
    <%= form.label :at %>
    <%= form.datetime_select :at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @location.lng %>
</p>

<p>
  <strong>At:</strong>
  <%= @location.at %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button type="button" onclick="reset()" class="btn btn-danger">Wipe</button>
</nav>

<div id="container">
  <div id="map"></div>
</div>
<script type="text/javascript">
    let vehiclesPath = {};
    let trackedVehiclesIds = [];
    let url = '/all_vehicles_locations';
    const center = {lat: 52.5308, lng: 13.47745};
    const cityBoundaries = 3500;


    const  reset =  ()=>{
            $.ajax({
                url: '/locations/reset',
                method: 'delete',
            });
        alert("Every thing wiped restart Simulator and refresh page")
    };

    /**
     *   Map options
     **/
    let map = new google.maps.Map(document.getElementById('map'), {
        center: center,
        zoom: 14,
        mapTypeId: google.maps.MapTypeId.ROADMAP,

        panControl: true,
        mapTypeControl: false,
        panControlOptions: {
            position: google.maps.ControlPosition.RIGHT_CENTER
        },
        zoomControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.LARGE,
            position: google.maps.ControlPosition.RIGHT_CENTER
        },
        scaleControl: false,
        streetViewControl: false,
        streetViewControlOptions: {
            position: google.maps.ControlPosition.RIGHT_CENTER
        }
    });

    /**
     *   Red Circle that surround door2door office
     * */
    const officeCircle = new google.maps.Circle({
        strokeColor: '#FF0000',
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: '#FF0000',
        fillOpacity: 0.05,
        map: map,
        center: center,
        radius: 3500
    });


    /**
     *   Check if the new car location is out of boundaries
     *   @params point => current vehicle location
     *   return Boolean
     * */
    const outOfBoundaries = (point) => {
        return google.maps.geometry.spherical.computeDistanceBetween
        (new google.maps.LatLng(point.lat, point.lng), new google.maps.LatLng(center.lat, center.lng)) > cityBoundaries;
    };

    /**
     *  make an ajax call if the car is out of boundaries to remove it
     * */
    const removeVehicle = (id) => {
        $.ajax({
            url: '/vehicles/' + id,
            method: 'delete'
        });

    };


    /**
     *   Closure for Every Vehicle which contains vehicle {path,marker}
     *
     * */
    const carRoute = () => {
        /** array that contains LatLng objects
         * */
        let carPathCoordinates = [];
        /** array that contains PolyLines objects
         * */
        let carPathPolyLines = [];

        /**   car svg
         * */
        const car = "M17.402,0H5.643C2.526,0,0,3.467,0,6.584v34.804c0,3.116,2.526,5.644,5.643,5.644h11.759c3.116,0,5.644-2.527,5.644-5.644 V6.584C23.044,3.467,20.518,0,17.402,0z M22.057,14.188v11.665l-2.729,0.351v-4.806L22.057,14.188z M20.625,10.773 c-1.016,3.9-2.219,8.51-2.219,8.51H4.638l-2.222-8.51C2.417,10.773,11.3,7.755,20.625,10.773z M3.748,21.713v4.492l-2.73-0.349 V14.502L3.748,21.713z M1.018,37.938V27.579l2.73,0.343v8.196L1.018,37.938z M2.575,40.882l2.218-3.336h13.771l2.219,3.336H2.575z M19.328,35.805v-7.872l2.729-0.355v10.048L19.328,35.805z";
        /**  icon options
         * */
        const icon = {
            path: car,
            scale: .6,
            strokeColor: '#C70039',
            strokeWeight: .10,
            fillOpacity: 1,
            fillColor: '#404040',
            offset: '5%',
            anchor: new google.maps.Point(10, 25)
        };

        /**   draw car on the map
         * */
        let marker = new google.maps.Marker({map: map, icon: icon});

        /**  @params => newlocation [vehicle new location]
         * */
        return (newlocation) => {

            /**
             * check if the new car location is out of boundaries
             * then remove car marker from map & remove traced line from map
             * */
            if (outOfBoundaries(newlocation)) {
                carPathPolyLines.forEach((poly) => poly.setMap(null));
                marker.setMap(null);
                return;
            }
            /**
             * if the car is not out of boundries
             * store the new location in array to draw it
             * */
            carPathCoordinates.push(new google.maps.LatLng(newlocation.lat, newlocation.lng));

            /**
             *   draw every new location
             *   and update car location and orientation
             * */
            const drawUpdatedLocation = () => {
                let carPath = new google.maps.Polyline({
                    path: carPathCoordinates,
                    geodesic: true,
                    strokeColor: '#2E4053',
                    strokeOpacity: 1,
                    strokeWeight: 2
                });
                carPath.setMap(map);
                carPathPolyLines.push(carPath);
                marker.setPosition(carPathCoordinates[carPathCoordinates.length - 1]);
                let end = carPathCoordinates.length > 1 ? carPathCoordinates[carPathCoordinates.length - 1] : carPathCoordinates[0];
                let start = carPathCoordinates.length > 1 ? carPathCoordinates[carPathCoordinates.length - 2] : carPathCoordinates[0];
                const heading = google.maps.geometry.spherical.computeHeading(start, end);
                icon.rotation = heading;
                marker.setIcon(icon);
            };

            drawUpdatedLocation();
        }
    };


    /**
     * [mark office location ]
     */
    function door2doorOffice() {
        new google.maps.Marker({map: map, position: {lat: 52.5308, lng: 13.47745}});
    }

    /**
     * On dom load
     * Inititalize all data
     * get vehicles last location every 3 seconds
     * draw updated locations
     * remove vehicle from map if its out of boundaries
     */
    $(document).on('turbolinks:load', function () {

        door2doorOffice();

        trackedVehiclesIds = <%= raw Vehicle.all.map(&:id) %>


            /**
             * for every vehicle
             * create Closure which contain all the vehicle data
             */
            trackedVehiclesIds.forEach((vehicle) => {
                const progress = carRoute();
                vehiclesPath[vehicle] = progress
            });


        /**
         *  check every 3 seconds each vehicle last location
         *  then send that location to every vehicle closure to be drawn on maps
         *  if the vehicle is out of boundaries
         *  mark closure as undefined after deleting vehicle track from the map
         */
        window.setInterval(() => {
            $.get(url, (data, status) => {
                trackedVehiclesIds.forEach((vehicle) => {
                    if (data[vehicle].lat || data[vehicle].lng) {
                        /**
                         *  stored closures hash will be accessed by vehicle id
                         *  like this => vehiclesPath[vehicle_id]( new location)
                         *  then every vehicle closure will update the car location with the new location
                         *
                         */
                        vehiclesPath[vehicle](data[vehicle]);
                        if (outOfBoundaries(data[vehicle])) {
                            vehiclesPath[vehicle] = undefined;
                            trackedVehiclesIds.splice(trackedVehiclesIds.findIndex((element) => element === vehicle), 1);
                            removeVehicle(vehicle)
                        }
                    }
                });
            });

        }, 3000);
    });
</script>




<style>
  html {
    height: 100%
  }

  body {
    height: 100%;
    margin: 0;
    padding: 0;
  }

  #container {
    width: 100%;
    height: 100%
  }

  #map {
    width: 100%;
    height: 100%
  }

</style>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @vehicle.id %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>